# ESP32-S3 MicroPython固件构建配置文件

[esp-idf]
version = v5.0.2
mirror_url = https://gitee.com/EspressifSystems/esp-idf.git

[micropython]
mirror_url = https://github.com/micropython/micropython.git

[camera]
esp32_camera_url = https://github.com/espressif/esp32-camera
micropython_camera_url = https://github.com/lemariva/micropython-camera-driver

[build]
# 目标开发板 (ESP32_GENERIC 或 ESP32_GENERIC_S3)
default_board = ESP32_GENERIC_S3
# 是否清理之前的构建
clean_build = true
# 并行构建任务数 (-j参数)
parallel_jobs = 4

[pip]
# 使用国内镜像加速
index_url = http://mirrors.aliyun.com/pypi/simple
trusted_host = mirrors.aliyun.com